# Exceções: continuação
#
# Veja o código no editor. Execute o programa (obviamente incorreto).
#
# Verá a seguinte mensagem em resposta:
# Traceback (most recent call last):
# File "div.py", line 2, in 
# value /= 0
# ZeroDivisionError: division by zero
#
# output
#
# Este erro de exceção é chamado ZeroDivisionError.


value = 1
value /= 0
